name: To docx
on:                 # це подія, яка вказує коли буде запускатися workflow
  push:           # назва події - коли щось відбувається з issues
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: uses my repository
        uses: actions/checkout@v2
      - run: java -version
      - run: sudo apt install openjdk-8-jre
      - run: java -version
      - name: install libreoffice
        run: sudo apt-get install libreoffice
      - name: convert to pdf1
        run: sudo lowriter --convert-to pdf labs.docx
      - name: upload file from vm # вивантажує артефакт в файл текстовий рядок 
        uses: actions/upload-artifact@v2
        with:
          name: docx
          path: labs.*
