name: To docx
on:                 # це подія, яка вказує коли буде запускатися workflow
  issues:           # назва події - коли щось відбувається з issues
    types: pinned   # тип активності - прикрпілення
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: uses my repository
        uses: actions/checkout@v2
      - name: install unoconv
        run: sudo apt-get install unoconv
      - name: convert to pdf
        run: doc2pdf labs.docx
      - name: convert
        run: curl --form file=@labs.docx http://localhost/unoconv/pdf > labs.pdf	  
      - name: upload file from vm # вивантажує артефакт в файл текстовий рядок 
        uses: actions/upload-artifact@v2
        with:
          name: docx
          path: labs.*
