# самий прстий workflow, простіше я не придумав
# створює віртуалку і запускає там команду в bash
name: Hello world 1 # назва workflow  
on:                 # це подія, яка вказує коли буде запускатися workflow
  issues:           # назва події - коли щось відбувається з issues 
    types: pinned   # тип активності - прикрпілення  
# https://help.github.com/en/actions/reference/events-that-trigger-workflows#issues-event-issues 
jobs:               # перелік завдань
  job1:             # назва першого завдання
    runs-on: ubuntu-latest # тип машини, на якій виконувати завдання
    steps:                 # кроки
      - name: uses my repository
        uses: actions/checkout@v2
      - name: download file to vm
        uses: actions/download-artifact@v2
        with:
          name: log
          path: log.txt		
      - name: step1        # назва кроку  
        run: echo Hello world! >> count.txt # добавляє в файл текстовий рядок
      - name: upload file from vm
        uses: actions/upload-artifact@v2
        with: log		
